export const user = [
  {
    email: 'kjhagsdkjAustinAustin@gmail.com',
    name: 'Austin babe Austin',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Austin@gmail.com',
    name: 'Austin babe',
    gender: 'Male',
    role: 'admin',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Dany@gmail.com',
    name: 'Dany babe',
    gender: 'Male',
    role: 'customer',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
  {
    email: 'Molly@gmail.com',
    name: 'Molly babe',
    gender: 'Female',
    role: 'manager',
    active: true,
    verified: false,
    phoneNumber: '0987014578',
  },
];
